### ISSUE TITLE
TabRoute as initial route? (Dynamically setting initial route)

### ISSUE THREAD

**Issue by patmisch** [Qwikly/react-native-router-redux#10]
@malkomalko is this possible? I've tried setting initial route to the TabRoute and to a child Route but neither work properly. The latter appears to work initially, but it actually throws:

cannot read property 'getCurrentRoutes' of undefined

**Comment by malkomalko** [comment]
@patmisch in the example app, you should be able to set the initialRoute to "tab1" and this works fine for me.  Can you try that?  Then maybe let me know your setup?

**Comment by patmisch** [comment]
Yeah, it works fine there for me too. I have an async action that is verifying a user auth token against the server. I have my app container rendering an indicator while this is happening and once it completes it renders the Router(exactly as shown in example app). If I have the initial route set to a normal route everything works as expected. If I set the initial route to tab1 it renders the scene correctly, but for whatever reason it is throwing an error in my thunk action: cannot read property 'getCurrentRoutes' of undefined

**Comment by malkomalko** [comment]
@patmisch there are only two places where this can be happening and it looks like your nav ref is probably coming back as null.  Can you debug your app in chrome to see where the error is happening in the stack trace?

**Comment by patmisch** [comment]
It looks like navigator is missing from the payload in the createReducer function in ROUTER_CHANGE_TAB

**Comment by malkomalko** [comment]
Hmm... weird, it must be that the navigator ref is coming back as null somehow.  Can you throw a console.log/debugger somewhere around https://github.com/Qwikly/react-native-router-redux/blob/master/index.js#L169 and see if that's correct?  You can just do this right in the installed node_modules/react-native-router-redux directory.  It will log to the console when you debug in chrome.

**Comment by patmisch** [comment]
That is the case. It is rendering 2 times(after INIT). The first time nav is null and the second time it is there. It also appears the the ROUTER_PUSH action is not firing in this case.

It must have something to do with how I'm modifying the state and having the container component react to that.

**Comment by patmisch** [comment]
It seems like it might be caused by having state objects other than router mapped to props in the container you set up the router in. This results in strange re-renderings of the Router when other state objects are updated. Still trying to work out a good solution to dynamically determine the initial route...

**Comment by patmisch** [comment]
I managed to get this working correctly. Figured I'd leave my solution here in case anyone else ran into the same issue. It seems like the main issue was having props other than router mapped into the container. 

Rather than waiting on the authentication in the container where the routing is set up, I handled the async auth call outside of react-redux in the root component within ComponentWillMount. Once you've done whatever call you need to do to determine which route to initialize with, you then render your main container with react-redux and pass in the initial route as a prop.

 Basic example:


```javascript
componentWillMount() {
  store.dispatch(verifyToken(newState.auth.user))
  .then(() => {
    this.setState({loaded: true})
  });

}

render() {
  const initialRoute = store.getState().auth.user.token ? 'checkIn' : 'login';
  if(this.state.loaded) {
    return (
      <Provider store={store}>
        {() => <App initialRoute={initialRoute} /> }
      </Provider>
    )
  }
  else {
    return (
    <ActivityIndicatorIOS
      animating={true}
      style={styles.activity}
      size="large"
    />
    )
  }
}

```

**Comment by tigershen23** [comment]
I ran into this issue as well (with setting a TabRoute as the Initial) and didn't really have time to dive into the root cause, but this patch worked for me if anyone else runs into a similar issue: https://github.com/tigershen23/react-native-router-redux/commit/4be261fcc32211b36d1183bf95e31914b135357e
