### ISSUE TITLE
[fixed] cannot set default tabs other than tab1 ?

### ISSUE THREAD

**Issue by iZaL** [Qwikly/react-native-router-redux#14]
so when I route the app after sign in to tabBar.tab4() or any other tabs except tab1, the app will show a blank screen. Is this the intended behavior ? or is it allowed to route to any tabs ?
Im building an app in arabic and the default tab starts from the right, I also tried to reverse the tab order, but it still shows a blank screen with the first tab bar selected. any help ?

**Comment by plougsgaard** [comment]
I tried to reproduce by changing the `onPress` handler for `SignIn.js` to `tab4()`, but it works fine here.

Getting a blank screen sounds like some `render` function returning a falsy value. Have you tried checking out the example and just changing that one thing?

**Comment by iZaL** [comment]
Yes tried the example and changed just one thing, still shows a white screen with tabs but no content , no nav bar

**Comment by malkomalko** [comment]
@iZaL I also can't replicate this.  Ensure you are on the latest and greatest, you cd into the example folder and run `npm install` and then `react-native start`.

**Comment by iZaL** [comment]
updating to the latest version fixed the issue. ty @malkomalko  @plougsgaard
