### ISSUE TITLE
Issue with react-native 0.16.0

### ISSUE THREAD

**Issue by laeijebor** [Qwikly/react-native-router-redux#16]
Hi - great work, but seems to have an issue with react-native 0.16.0 - hangs when transforming (possibly babel 6 incompatible)

**Comment by malkomalko** [comment]
There is a PR that addresses the 0.16.0 upgrade.  I was away for a few days but will start looking at this over the next few days.

**Comment by laeijebor** [comment]
Many thanks, much obliged!

**Comment by DavoCg** [comment]
To use it with RN 0.16 i removed the .babelrc file in react-native-navbar module and modified the navBar.js file (as in the PR).

Build is OK, Transform is OK

But I think that navLeft and NavRight properties for custom nav component (pass to Route) are broken.

**Comment by malkomalko** [comment]
Now that I have time I'll be rounding this out for the latest RN sometime this week.  Thanks everybody!

**Comment by malkomalko** [comment]
Pulled in the PR
