### ISSUE TITLE
questions about actions.routes

### ISSUE THREAD

**Issue by atom2ueki** [Qwikly/react-native-router-redux#17]
I want to use `actions.routes` out of the render() in another function.

```javascript
...
  _onPressLogin(actions) {
      console.log(actions);
      return actions.routes.signIn();
  }

  render() {
    const { assets, actions } = this.props;
    return (
      <View style={styles.container}>
        <TouchableHighlight onPress={this._onPressLogin.bind(this, actions)} style={[styles.btn, styles.loginBtn]}>
          <View style={styles.btnStyle}>
            <Text style={[styles.btnText, styles.loginBtnText]}>Login</Text>
          </View>
        </TouchableHighlight>
      </View>
    );
  }
...
```
but it won't work,  ` console.log(actions)` able to print the routes, but it just cannot redirect to the page.

simply said, `actions.routes.tabBar.tab1()` cannot work if put into a function.

**Comment by malkomalko** [comment]
@atom2ueki please see https://github.com/Qwikly/react-native-router-redux/issues/8

**Comment by atom2ueki** [comment]
@malkomalko I don't think that's the answer of my question, is that solved call a route from a function out of render()

**Comment by oney** [comment]
@atom2ueki 
Try this
```javascript
  _onPressLogin(actions) {
      console.log(actions);
      return actions.routes.signIn()();
  }
```

**Comment by jolyonruss** [comment]
@atom2ueki did you resolve this?

Another option would be to destructure the actions in the _onPressLogin method, like this:

```
_onPressLogin(){
    const { actions } = this.props;
    return actions.routes.signIn();
}
```
