### ISSUE TITLE
Slow tab changing with redux-logger

### ISSUE THREAD

**Issue by Sunify** [Qwikly/react-native-router-redux#2]
When i run app on device with enabled redux-logger middleware, i have really slow (≈10 sec) tab changes. Without middleware all works good.

1. I press on tab
2. Action ROUTER_CHANGE_TAB emits
3. 10 sec freeze
4. Action ROUTER_CHANGE_TAB emits again and then tab really change

**Comment by malkomalko** [comment]
I was having similar problems with redux-logger without my routing component on react-native redux applications.  I'll see if I can track this down.

**Comment by malkomalko** [comment]
@Sunify I'm going to close this for now and will revisit later.

**Comment by shtefanntz** [comment]
Hello everyone,

I can confirm there's a visible overhead due to redux-logger when changing routes. Thanks for pointing it out!

**Comment by tarun29061990** [comment]
Its happening for me as well, I removed redux-logger, thunk and there is no middleware in my application, May be there is some other reason for the slow transition. Please help
