### ISSUE TITLE
Add dynamic route parameters example?

### ISSUE THREAD

**Issue by tijs** [Qwikly/react-native-router-redux#31]
Am i right to conclude that this router does not support parameters for routes? For instance i can have a route named `detail` and then go there by calling `actions.routes.detail()` but as far as i can tell i can't have a route named `detail/:name` (or something along those lines) and then call `actions.routes.detail('myname')` thus allowing the detail view to be dynamic.

The example uses a parameter as part of the component call but i haven't been able to both set a property that is then uses in the component attribute of the route (`component={Detail(this.props.name)}`) while also making the tap action call the routes action. 

I'm probably overlooking something simple so maybe an example could be added to the current example code?

**Comment by davidsims9t** [comment]
I'm successfully using routing with with parameters. Here's how I'm doing it:

`this.props.actions.routes.detail(routeProps)`

Then in your detail view you can access your passed props by using:

`this.props.routerData.routeProps`

**Comment by tijs** [comment]
@davidsims9t thanks. looks like i was not looking in the routerData object most likely!
