### ISSUE TITLE
Lose data on pop

### ISSUE THREAD

**Issue by Sunify** [Qwikly/react-native-router-redux#4]
For example, i have two entity on one type and route for view it.
I want to view one of this entity and make `actions.entity({ id: 1 })()`, then i go to some other route, press «Back» and see empty screen, because router.data is something like `{ num: 1, name: 'someEntity' }` but should be `{ num: 1, name: 'someEntity', id: 1 }`. Correct me if i am wrong.

**Comment by malkomalko** [comment]
@Sunify you should be able to access the props.routerData property in your component.  That should have all the data you pass to it.  Let me know if I'm not understanding correctly.

https://github.com/Qwikly/react-native-router-redux/blob/6a6102d0c3d952cb70b1f7e72dbf7906500ea9fe/index.js#L265
