### ISSUE TITLE
NavBar components

### ISSUE THREAD

**Issue by DavoCg** [Qwikly/react-native-router-redux#7]
Hi,

First thanks for the work you have done !
I just want to know if it's possible to add custom right and left elements in the navBar for a specified route ?

If it's not the case is it in the road map ? 

Thanks buddies ;)

**Comment by malkomalko** [comment]
Hi DavoCg,

Take a look at https://github.com/Qwikly/react-native-router-redux/blob/master/src/NavBar.js#L4 for the time being until I update the README with some more documentation.

You have a few options here to pass down props to each route:

navLeft/navRight: This can be your own custom react component or whatever you need.
navLeftHandler/navRightHandler: action to fire on click if not using a custom navLeft/navRight.
navLeftStyle/navRightStyle: styles to mixin if not using a custom navLeft/navRight.
navLeftColor/navRightColor: label color if not using a custom navLeft/navRight.
navLeftTitle/navRightTitle: title if not using a custom navLeft/navRight.

Hopefully this helps.

**Comment by DavoCg** [comment]
Thanks for your answer !
I've seen this but when i try to pass a custom component to navLeft the if statement
https://github.com/Qwikly/react-native-router-redux/blob/master/src/NavBar.js#L5 is never reach because  ``` props.navLeft._isReactElement ``` is always undefined.

my custom component is really simple: 

```
class CustomLeft extends Component {
    constructor(props){
        super(props);
    }
    render(){
        return(
            <Text>Custom</Text>
        )
    }
}
```

Maybe I miss something !

Thanks

**Comment by DavoCg** [comment]
Sorry we can close this issue i figured out by myself my mistake

```
<Route name="profile" component={Profile} title={'Mon compte'} navLeft={CustomLeft}/>
```

instead of: 

```
<Route name="profile" component={Profile} title={'Mon compte'} navLeft={<CustomLeft />}/>
```

I need to sleep !

**Comment by malkomalko** [comment]
:sleeping:

**Comment by tantou** [comment]
@DavoCg  I do the same you did, But `props.navLeft._isReactElement` is still always undefined.
I use react native `0.17.0`
