### ISSUE TITLE
Router actions outside of components

### ISSUE THREAD

**Issue by patmisch** [Qwikly/react-native-router-redux#8]
How do you recommend changing scenes after performing other actions?

**Comment by patmisch** [comment]
I've managed to figure this out by passing actions.routes from the container component into the thunk action creator and calling the route action from there. Not sure if there is a better way or not, but this seems to work fine.

**Comment by malkomalko** [comment]
Alternatively you can do something like:

```

**Comment by malkomalko** [comment]
Alternatively you can do something like this in your custom actions:

```javascript
import { actions as routerActions } from 'react-native-router-redux';

export function someOtherAction() {
  return (dispatch) => {
    dispatch({
      type: routerActions.actionTypes.ROUTER_PUSH,
      payload: {
        name: 'nameOfRoute',
        tabBarName: 'nameOfTabRoute', // if in a tab bar
        data: { // this will be passed as props.routerData in your component
          title: 'Some new title', // ... and mixed in to header/footer props
        },
      },
    });
  };
}
```

Hopefully this gives you another idea.

**Comment by patmisch** [comment]
Great. Thanks!

**Comment by malkomalko** [comment]
@patmisch no problem.  Let me know if you run into anything else.
