### ISSUE TITLE
example is not working

### ISSUE THREAD

**Issue by yusufseyrek** [Qwikly/react-native-router-redux#9]
I got "Application ReduxRouter has not been registered." error on AppRegistry.registerComponent function. Btw i didn't change anything on example. Does anyone know why i am getting this error ?

Thanks

**Comment by malkomalko** [comment]
I am unable to replicate this error @yusufseyrek.  Are you running `react-native start` from inside the example/ReduxRouter directory?

**Comment by yusufseyrek** [comment]
Thanks @malkomalko! i just didn't realize that

**Comment by tarun29061990** [comment]
Which react version this example is supporting because there is no react dependency in package.json?
